version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"

  # /
  server1:
    build: ./nginx/


  # /health
  server2:
    build: 
      context: ./app/
      dockerfile: Dockerfile-server2
  
  # /test
  server3:
    build: 
      context: ./app/
      dockerfile: Dockerfile-server3